---
- name: Ensure Prometheus Proxy install directory exists.
  file:
    path: "{{ prometheus_proxy_install_dir }}"
    owner: root
    group: root
    state: directory
    mode: 0755

- name: Ensure Prometheus Proxy configuration directory exists.
  file:
    path: "{{ prometheus_proxy_config_dir }}"
    owner: root
    group: root
    state: directory
    mode: 0755

- name: Download Prometheus Proxy binary.
  get_url:
    url: "{{ prometheus_proxy_bin_url }}"
    dest: "{{ prometheus_proxy_install_dir }}/prometheus-proxy.jar"
    owner: root
    group: root
    mode: 0755
  when: prometheus_proxy_enabled

- name: Download Prometheus Proxy agent binary.
  get_url:
    url: "{{ prometheus_proxy_agent_bin_url }}"
    dest: "{{ prometheus_proxy_install_dir }}/prometheus-proxy-agent.jar"
    owner: root
    group: root
    mode: 0755
  when: prometheus_proxy_agent_enabled

- name: Copy Prometheus Proxy agent systemd unit file into place (for systemd systems).
  template:
    src: prometheus-proxy-agent.unit.j2
    dest: /etc/systemd/system/prometheus-proxy-agent.service
    owner: root
    group: root
    mode: 0755
  when: prometheus_proxy_bin_url and ansible_service_mgr == 'systemd'

- name: Copy Prometheus Proxy agent init script into place.
  template:
    src: prometheus-proxy-agent.init.j2
    dest: /etc/init.d/prometheus-proxy-agent
    owner: root
    group: root
    mode: 0755
  when: prometheus_proxy_agent_enabled and ansible_service_mgr != 'systemd'

- name: Copy Prometheus Proxy systemd unit file into place (for systemd systems).
  template:
    src: prometheus-proxy.unit.j2
    dest: /etc/systemd/system/prometheus-proxy.service
    owner: root
    group: root
    mode: 0755
  when: prometheus_proxy_enabled and ansible_service_mgr == 'systemd'

- name: Copy Prometheus Proxy init script into place.
  template:
    src: prometheus-proxy.init.j2
    dest: /etc/init.d/prometheus-proxy
    owner: root
    group: root
    mode: 0755
  when: prometheus_proxy_enabled and ansible_service_mgr != 'systemd'

- name: Ensure Prometheus Proxy agent is enabled and will start on boot.
  service: name=prometheus-proxy-agent state=started enabled=yes
  when: prometheus_proxy_agent_enabled

- name: Ensure Prometheus Proxy is enabled and will start on boot.
  service: name=prometheus-proxy state=started enabled=yes
  when: prometheus_proxy_enabled

- name: Copy Prometheus Proxy agent configuration
  template:
    src: apps.conf.j2
    dest: "{{ prometheus_proxy_config_dir }}/apps.conf"
    owner: root
    group: root
    mode: 0755
  notify: restart prometheus-proxy-agent
  when: prometheus_proxy_agent_enabled
